# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Fri Jan  3 13:37:07 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(709, 528)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.outputsGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.outputsGroupBox.setObjectName(_fromUtf8("outputsGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.outputsGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.outputsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.outputsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.outputsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.genesGraphImageLabel = QtGui.QLabel(self.outputsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genesGraphImageLabel.sizePolicy().hasHeightForWidth())
        self.genesGraphImageLabel.setSizePolicy(sizePolicy)
        self.genesGraphImageLabel.setText(_fromUtf8(""))
        self.genesGraphImageLabel.setObjectName(_fromUtf8("genesGraphImageLabel"))
        self.horizontalLayout_2.addWidget(self.genesGraphImageLabel)
        self.statesGraphImageLabel = QtGui.QLabel(self.outputsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statesGraphImageLabel.sizePolicy().hasHeightForWidth())
        self.statesGraphImageLabel.setSizePolicy(sizePolicy)
        self.statesGraphImageLabel.setText(_fromUtf8(""))
        self.statesGraphImageLabel.setObjectName(_fromUtf8("statesGraphImageLabel"))
        self.horizontalLayout_2.addWidget(self.statesGraphImageLabel)
        self.simplifiedStatesGraphImageLabel = QtGui.QLabel(self.outputsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simplifiedStatesGraphImageLabel.sizePolicy().hasHeightForWidth())
        self.simplifiedStatesGraphImageLabel.setSizePolicy(sizePolicy)
        self.simplifiedStatesGraphImageLabel.setText(_fromUtf8(""))
        self.simplifiedStatesGraphImageLabel.setObjectName(_fromUtf8("simplifiedStatesGraphImageLabel"))
        self.horizontalLayout_2.addWidget(self.simplifiedStatesGraphImageLabel)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.outputsGroupBox)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_3.addWidget(self.progressBar, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.outputsGroupBox, 3, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.goButton = QtGui.QPushButton(self.centralwidget)
        self.goButton.setObjectName(_fromUtf8("goButton"))
        self.verticalLayout_3.addWidget(self.goButton)
        self.inlutsGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.inlutsGroupBox.setObjectName(_fromUtf8("inlutsGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.inlutsGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.kSlider = QtGui.QSlider(self.inlutsGroupBox)
        self.kSlider.setMaximum(20)
        self.kSlider.setOrientation(QtCore.Qt.Horizontal)
        self.kSlider.setObjectName(_fromUtf8("kSlider"))
        self.gridLayout_4.addWidget(self.kSlider, 3, 1, 1, 1)
        self.kLabel = QtGui.QLabel(self.inlutsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.kLabel.setFont(font)
        self.kLabel.setObjectName(_fromUtf8("kLabel"))
        self.gridLayout_4.addWidget(self.kLabel, 3, 0, 1, 1)
        self.nLabel = QtGui.QLabel(self.inlutsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.nLabel.setFont(font)
        self.nLabel.setObjectName(_fromUtf8("nLabel"))
        self.gridLayout_4.addWidget(self.nLabel, 1, 0, 1, 1)
        self.nSlider = QtGui.QSlider(self.inlutsGroupBox)
        self.nSlider.setMaximum(20)
        self.nSlider.setOrientation(QtCore.Qt.Horizontal)
        self.nSlider.setObjectName(_fromUtf8("nSlider"))
        self.gridLayout_4.addWidget(self.nSlider, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.inlutsGroupBox)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "NK Network Main Window", None, QtGui.QApplication.UnicodeUTF8))
        self.outputsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Gene Connections Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "States Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "SimplifiesStatesGraph", None, QtGui.QApplication.UnicodeUTF8))
        self.goButton.setText(QtGui.QApplication.translate("MainWindow", "go", None, QtGui.QApplication.UnicodeUTF8))
        self.inlutsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.kLabel.setText(QtGui.QApplication.translate("MainWindow", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.nLabel.setText(QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

